DELIMITER $$
CREATE TRIGGER update_tot_cred
AFTER UPDATE ON TAKES
FOR EACH ROW
BEGIN
DECLARE CR_CRED INT;
IF OLD.GRADE IS NULL 
AND NEW.GRADE IN ('A','B','C')
THEN
SELECT CREDITS INTO CR_CRED 
FROM COURSE 
WHERE COURSE_ID=NEW.COURSE_ID;
UPDATE STUDENT
SET TOTAL=TOTAL+CR_CRED 
WHERE ID=NEW.ID; 
END IF;
END $$
DELIMITER ;