DELIMITER $$
CREATE PROCEDURE register_student
(IN STD_ID VARCHAR(5),
IN CR_ID VARCHAR(8),
IN SEC_ID VARCHAR(8),
IN SEMESTER VARCHAR(6),
IN YEAR_VAL INT) 
BEGIN 
INSERT INTO TAKES(ID,course_id,sec_id,semester,year,grade)VALUES (STD_ID,CR_ID,SEC_ID,SEMESTER,YEAR_VAL,NULL);
END $$
DELIMITER ;